spring:
  profiles:
    active: dev
  application:
    name: product-service
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: systempass
server:
  port: 19093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/



management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0

